# Generated by Django 3.1.5 on 2021-01-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('horario_funcionamento', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('idade_min', models.IntegerField()),
                ('aprovado', models.BooleanField(default=False)),
            ],
        ),
    ]
